### ISSUE TITLE
Can't enable it in project setting

### ISSUE THREAD

**Issue by Katrina9999931** [GDUcrash/BetterTabContainer#2]
Hi, 

I installed it but after I can't enable it in project setting because it doesn't appear. I have godot version 4.1.1

Thank you

Martine

**Comment by azureitte** [comment]
Have you installed the `main` or the `4.0` branch of the addon? Since you're using Godot 4.x, you should download the latter.

**Comment by Katrina9999931** [comment]
I installed the 4.0

**Comment by azureitte** [comment]
The issue should be fixed now, try re-downloading the addon

**Comment by Katrina9999931** [comment]
I retried and it didn't work

**Comment by azureitte** [comment]
It does work for me on Godot 4.1.1, so I can't reproduce the issue

**Comment by azureitte** [comment]
Make sure you downloaded the latest fix from the `4.0` branch and replaced the addon in your project's folder

**Comment by Katrina9999931** [comment]
Hi,
Thank you for your reply,
I'm new to godot. I retry. It's appears now in the project plugin, but I have an error when I try to enable it.  I download the one on the asset library better tab container 1.1. I copied the folder addons in my project.
Martine

**Comment by azureitte** [comment]
Try installing the version from GitHub https://github.com/GDUcrash/BetterTabContainer/tree/4.0. The asset library version has not yet been updated

**Comment by Katrina9999931** [comment]
Thanks a lot ! It's working !

**Comment by Katrina9999931** [comment]
Have a good day
